apiVersion: v1
kind: Service
metadata:
  name: devops-infra-service
spec:
  type: NodePort
  selector:
    app: devops-infra-app
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30007
